crawler:
  driver:
    path: ./

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.165.180.203:51636/goneda_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true