name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:      
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gonedaweb build
        run: ./gradlew goneda-web:build
    
  deploy:
    needs: build
    name: Deploy Steps
    runs-on: ubuntu-latest
    steps:
      - name: Deliver File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/libs/*.jar"
          strip_components: 1
          target: "source"
        
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            SOURCE_DIR=source/build/libs
            FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
            PID=`ps -ef | grep goneda | grep sudo | grep -v "bash -c" | awk '{print $2}'`

            if [ -z "$PID" ]; then
                    echo "#### THERE IS NO PROCESS ####"
            else
                    echo "#### KILL $PID ####"
                    sudo kill $PID
            fi

            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"

            sudo java -jar $SOURCE_DIR/$FILE_NAME > /dev/null 2>&1 &
          

